"""
I've come to realize that with just a single dry electrode on FP1,
it is extremely hard to decode concentration values because of all
of the noise. I've pivoted to looking at Alpha Synchronization / 
Desynchronization via opening and closing my eyes.

When I close my eyes, my visual cortex stops receiving visual input
and this should generate a massive 8-12 Hz Alpha surge right across
the frontal lobe (and should hopefully be more detectable by my 
single electrode).

This method is distinct from EOG and still falls within the EEG
category because alpha wave modulation is generated by synchronized 
neural firing in the brain's visual cortex, rather than the movement 
of the eyeball. Because it produces a sustained, frequency-specific 
power spike while the eyes sit completely motionless behind closed lids, 
I believe this is still a pure neuro-electrical oscillation rather 
than an eye movement artifact.
"""